stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - kubectl apply -f persistent-volume.yaml
    - kubectl apply -f persistent-volume-claim.yaml
    - kubectl apply -f deployment.yaml
    - kubectl apply -f cronjob.yaml
  environment:
    name: production
  only:
    - main
