apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
          volumeMounts:
            - name: my-volume
              mountPath: /app
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc
